spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: rcdev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  error:
    include-exception: true      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: never  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

logging:
  level:
    org.hibernate: debug