openapi: 3.0.1
info:
  title: Roadcapture API
  description: Roadcapture API Description
  version: 0.1.0
servers:
- url: http://localhost:8080
tags:
- name: users
  description: Users related resources
paths:
  /users:
    post:
      tags:
      - users
      operationId: user
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/users-725712466'
            examples:
              user-signup:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abdc1234\",\"\
                  username\":\"user\"}"
              user-signup-email-duplicate:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abcd1234\",\"\
                  username\":\"user\"}"
              user-signup-email-mismatch:
                value: "{\"email\":\"test\",\"password\":\"abdc1234\",\"username\"\
                  :\"user\"}"
              user-signup-nickname-longer:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abdc1234\",\"\
                  username\":\"usernameusern\"}"
              user-signup-nickname-shorter:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abdc1234\",\"\
                  username\":\"u\"}"
              user-signup-password-longer:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789\"\
                  ,\"username\":\"username\"}"
              user-signup-password-mismatch:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abcdefgh\",\"\
                  username\":\"username\"}"
              user-signup-password-shorter:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abcd123\",\"\
                  username\":\"username\"}"
              user-signup-username-duplicate:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abcd1234\",\"\
                  username\":\"user\"}"
              user-signup-username-longer:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abdc1234\",\"\
                  username\":\"usernameusern\"}"
              user-signup-username-shorter:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abdc1234\",\"\
                  username\":\"u\"}"
              users:
                value: "{\"email\":\"test@gmail.com\",\"password\":\"abdc1234\",\"\
                  username\":\"u\"}"
      responses:
        "201":
          description: "201"
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users486549215'
              examples:
                user-signup-email-duplicate:
                  value: "{\"code\":\"USR-002\",\"status\":400,\"message\":\"중복된 이\
                    메일의 계정이 존재합니다.\",\"errors\":[]}"
                user-signup-email-mismatch:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"email\",\"value\":\"\
                    test\",\"reason\":\"must be a well-formed email address\"}]}"
                user-signup-nickname-longer:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"username\",\"value\"\
                    :\"usernameusern\",\"reason\":\"size must be between 2 and 12\"\
                    }]}"
                user-signup-nickname-shorter:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"username\",\"value\"\
                    :\"u\",\"reason\":\"size must be between 2 and 12\"}]}"
                user-signup-password-longer:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"password\",\"value\"\
                    :\"abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789\"\
                    ,\"reason\":\"length must be between 8 and 64\"}]}"
                user-signup-password-mismatch:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"password\",\"value\"\
                    :\"abcdefgh\",\"reason\":\"must match \\\"^(?=.*[A-Za-z])(?=.*\\\
                    \\d)[A-Za-z\\\\d]+$\\\"\"}]}"
                user-signup-password-shorter:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"password\",\"value\"\
                    :\"abcd123\",\"reason\":\"length must be between 8 and 64\"}]}"
                user-signup-username-duplicate:
                  value: "{\"code\":\"USR-005\",\"status\":400,\"message\":\"중복된 닉\
                    네임의 계정이 존재합니다.\",\"errors\":[]}"
                user-signup-username-longer:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"username\",\"value\"\
                    :\"usernameusern\",\"reason\":\"size must be between 2 and 12\"\
                    }]}"
                user-signup-username-shorter:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"username\",\"value\"\
                    :\"u\",\"reason\":\"size must be between 2 and 12\"}]}"
                users:
                  value: "{\"code\":\"CMM-001\",\"status\":400,\"message\":\"Invalid\
                    \ Input Value\",\"errors\":[{\"field\":\"username\",\"value\"\
                    :\"u\",\"reason\":\"size must be between 2 and 12\"}]}"
components:
  schemas:
    users-725712466:
      type: object
      properties:
        password:
          type: string
          description: 사용자 비밀번호입니다. 영문 숫자 조합 최소 8자 이상에서 최대 64자 이하여야 합니다.
        email:
          type: string
          description: 사용자 이메일입니다. 이메일 형식이어야 합니다.
        username:
          type: string
          description: 사용자 이름입니다. 최소 2자 이상에서 최대 12자 이하여야 합니다.
    users486549215:
      type: object
